- name: Kubernetes Dependencies
  hosts: leader
  vars:
    services:
      - service1
      - service2
      - service3
  tasks:
    - name: Test loop
      shell: "echo {{ item }}"
      loop: "{{ services }}"
