- name: Kubernetes Dependencies
  hosts: leader
  remote_user: root
  become: yes
  tasks:
    - name: Test url_get
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /root/test.txt
        force: true
